name: GitHub Pets

on:
  schedule:
    - cron: "0 */6 * * *" # Tự động cập nhật mỗi 6 tiếng
  workflow_dispatch: # Cho phép bạn bấm chạy thủ công bất cứ lúc nào

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pets
        uses: readme-pets/github-actions-readme-pets@v1 # Đã cập nhật lại tên tổ chức mới ở đây
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pets: "cat, dog, crab"

      - name: Commit & Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update pets in README" || exit 0
          git push
